version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: novacare-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: novacare_root
      MYSQL_DATABASE: NovaCare_db
      MYSQL_USER: basant_admin
      MYSQL_PASSWORD: NovaCare_2026_B
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
